# Generated by Django 5.0.4 on 2024-04-25 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Marketplace_Project', '0001_initial'),
    ]

    operations = [
    ]
