# Generated by Django 5.0.4 on 2024-05-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketplace_Project', '0002_auto_20240425_0333'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomuser',
            name='bio_info',
            field=models.TextField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='randomuser',
            name='years_of_experience',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
