# Generated by Django 5.0.4 on 2024-05-10 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Marketplace_Project', '0004_newuser_remove_order_products_remove_order_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewUser',
        ),
    ]
